import Head from 'next/head';
import Link from 'next/link';
import { useState, useEffect } from 'react';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Try Disital Filter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen from-cyan-400 bg-gradient-to-br to-blue-500">
        <div className="max-w-4xl flex flex-col items-center justify-center pt-12 mx-auto">
          <Link href="iir_bandpass">
            <a>IIR bandpass</a>
          </Link>
        </div>
      </div>
    </div>
  );
}
